# 2. Data Preprocessing - Akkadian to English Translation
## Aaron Dichoso & Luis Razon

This notebook details the steps performed for preprocessing the cleaned dataset used in the Deep Past Challenge for Translating Akkadian Text to English.
The competition can be accessed in this link: https://www.kaggle.com/competitions/deep-past-initiative-machine-translation/data

Run this notebook AFTER running "1. Cleaning".

In [1]:
import pandas as pd
import numpy
print(numpy.__version__)
print(pd.__version__)

cleaned_complete_df = pd.read_csv("processed/cleaned_train_complete.csv")
cleaned_incomplete_df = pd.read_csv("processed/cleaned_train_incomplete.csv")

cleaned_complete_df.sample(5)

2.4.1
3.0.0

,oare_id,transliteration,translation
1352,dfa4f36e-eb92-45fd-800c-514ba0af5966,<big_gap> i-dì-in-ma ša-lim-a-šùr ù DUMU a-mur...,"<big_gap> the colony rendered a verdict, and Š..."
880,8e6f8e72-25e0-44fe-a498-4818636a8861,a-na a-lá-hi-im qí-bi-ma um-ma <big_gap> šu-ma...,To Ali-ahum from <big_gap>: If you observe <bi...
18,02df45ee-6d74-46fb-9870-3e546ce7d304,a-na PUZUR4-(d)IM lá-dí-a en-um-a-šur en-na-sú...,"To Puzur-Adad, Ladiya, Ennam-Aššur, Enna-Suen,..."
1487,f74875b8-6f58-4bfa-a4da-ac136a0e406a,um-ma ša-lim-a-šur-ma a-na i-dí-a-bi-im e-na-n...,"From Šalim-Aššur to Iddin-abum, Ennānum, Inah-..."
968,9b14060a-4325-4e83-aab8-2e717d743480,kà-ru-um ṣa-he-er GAL dí-nam i-dí-in-ma ša-lim...,The plenary assembly of the colony passed a ve...

The goal of this notebook is to tokenize the data using Byte-Pair Encoding so that it can be trained on networks that can accept sequential data like LSTM and transformers.
First, we look for all text in the transliteration that are contained in parentheses to find the determinatives. These are prefixes/suffixes attached to words that give it special meanings.

In [2]:
#Parentheses in the cleaned data were not removed for determinatives, so look inside these for them.
def parse(text):
    stack = []
    for char in text:
        if char == '(':
            #stack push
            stack.append([])
        elif char == ')':
            yield ''.join(stack.pop())
        elif len(stack) > 0:
            #stack peek
            stack[-1].append(char)
    
    return stack

parses = []
for i, row in pd.concat([cleaned_complete_df, cleaned_incomplete_df]).iterrows():
    parses.append(tuple(parse(row['transliteration'])))

#Loop through parse tuples
determinatives = dict()
for p in parses:
    for d in p:
        if determinatives.get(d):
            determinatives[d] += 1
        else:
            determinatives[d] = 1

determinatives

{'d': 482, 'ki': 383, 'TÚG': 192, 'HI': 1}

These determinatives are isolated and then tokenized into corresponding english meanings according to the dataset.

In [3]:
DET_TOKENS = {
    "(d)": "<god>",
    "(HI)": "<star>",
    "(ki)": "<place>",
    "(lu2)": "<person>",
    "(e2)": "<building>",
    "(uru)": "<city>",
    "(kur)": "<land>",
    "(mi)": "<female>",
    "(m)": "<male>",
    "(gesh)": "<wood>",
    "(TÚG)": "<textile>",
    "(dub)": "<tablet>",
    "(id2)": "<river>",
    "(mushen)": "<bird>",
    "(na4)": "<stone>",
    "(kush)": "<hide>",
    "(u2)": "<plant>",
}

In [4]:
for key in DET_TOKENS.keys():
    cleaned_complete_df['transliteration'] = cleaned_complete_df['transliteration'].str.replace(key, DET_TOKENS[key])
    cleaned_incomplete_df['transliteration'] = cleaned_incomplete_df['transliteration'].str.replace(key, DET_TOKENS[key])

In [5]:
#Sanity Checkpoint: continually repeat running this cell to view your processed data so far.
cleaned_complete_df.sample(5)

,oare_id,transliteration,translation
432,4433bc7d-6c00-4d83-a763-c6a6921c3537,1/2 ma-na KÙ.BABBAR ṣa-ru-pá-am iš-tí a-šùr-na...,1/2 mina of refined silver due from Aššur-nādā...
1051,aa84dc4a-b81b-4519-9d60-797b7ba276c8,KIŠIB kà-ri-im kà-ni-iš kà-ru-um dí-nam i-dí-i...,Seal of the Kanesh colony. The colony has pass...
78,0bc255d7-4dcb-4763-8d8b-2d4af41720b4,2 GÚ 10 ma-na AN.NA ku-nu-ki 52 TÚG SIG5 3 ANŠ...,"2 talents 10 minas of sealed tin, 52 good text..."
276,2c0fa8ce-2871-4912-a4c9-f01f07f56dc0,a-na be-lu-ba-ni ù a-lá-hi-im qí-bi-ma um-ma z...,To Bēlum-bāni and Ali-ahum from Zukuwa: 2 extr...
48,07e7a1b1-4d8d-4363-996b-e29d43fe77e4,1 ku-ta-num 2 šu-re-en6 ša šu-ku-bi-im a-na 2/...,1 textile and 2 dark textiles belonging to Šu-...

In [ ]:
import re

#Additional cleaning done because of tokenization. Separate all tokens that are attached to words with spaces to prep the dataset for BPE.
#NOTE: Try NOT running this and see if model results can change. This is a completely optional preprocessing step.
cleaned_complete_df['transliteration'] = cleaned_complete_df['transliteration'].str.replace(re.compile(r'(\w+)*<(\w+)>(\w+)*'), r'\1 <\2> \3', regex=True)
cleaned_incomplete_df['transliteration'] = cleaned_incomplete_df['transliteration'].str.replace(re.compile(r'(\w+)*<(\w+)>(\w+)*'), r'\1 <\2> \3', regex=True)

In [ ]:
#Sanity Checkpoint.
cleaned_complete_df.sample(5)

,oare_id,transliteration,translation
869,8c167b5b-efde-466d-a6d2-06faf49a637c,i-na 1-ma-na KÙ.BABBAR ša a-na a-lim <place> ...,From the 1 mina of silver which I had Bēlānum ...
602,5f264cf3-196b-4105-9d75-b6a6aedaae97,šu-ma um-me-a-an ša-lim-a-šur a-na AN.NA ù <b...,If Šalim-Ašsur's investors raise claim against...
734,772ba716-bbe5-4bbf-949f-ac4767147189,KIŠIB a-lu-lá-a-na en-nam-a-šur,Sealed by Alulaya to Ennam-Aššur.
1203,c3cbcb45-835e-4139-a6e2-ced1d7882bca,<big_gap> -na GÍR ša a-šur iṣ-ba-at-ma a-šur-...,<big_gap>na seized Aššur's dagger and Aššur-ma...
996,a1251a33-431a-401a-b678-d8b20181ddda,4 me-at sí-pá-ra-tum 18 šé-na-tum 34 šé-na-tum...,"400 bronze pins, 18 shoes, 34 children's shoes..."

In [ ]:
cleaned_complete_df.to_csv("processed/processed_train_complete_untokenized.csv")
cleaned_incomplete_df.to_csv("processed/processed_train_incomplete_untokenized.csv")

## Tokenized Dataset

To tokenize the dataset, we first encode the characters into tokens. We use Byte-Pair Encoding (BPE) for this, as it offers a good balance between vocabulary size and character length compared to other encoding techniques like character encoding (small vocab size, but does not learn spelling) and word encoding (large vocabulary). 

Byte-Pair Encoding works by finding the most common substrings across the dataset and using those as individual tokens to be used for encoding (Source: https://www.geeksforgeeks.org/nlp/byte-pair-encoding-bpe-in-nlp/). Thus, it lends itself well to the Akkadian transliterations, which are made up of several substrings seperated by dashes. the determinatives pre/appended on words are also a key characteristic in the Akkadian transliterations which BPE naturally fits for this use case.

In [8]:
import utils.bpe as bpe
import importlib

importlib.reload(bpe)

BPE = bpe.BytePairEncoder()
BPE_akk = bpe.BytePairEncoder()
cleaned_complete_df["transliteration"] = cleaned_complete_df["transliteration"].astype("object")
cleaned_incomplete_df["transliteration"] = cleaned_incomplete_df["transliteration"].astype("object")
cleaned_complete_df["translation"] = cleaned_complete_df["translation"].astype("object")
cleaned_incomplete_df["translation"] = cleaned_incomplete_df["translation"].astype("object")

#Get the whole text from across the dataset for BPE
akkadian_only = ""
whole_text = ""
for i, row in pd.concat([cleaned_complete_df, cleaned_incomplete_df]).iterrows():
    #Seperate entries by <sos> (Start of Sequence) and <eos> (End of Sequence) tokens.
    new_row = " <sos> " + row['transliteration'] + " <eos> "
    akkadian_only += new_row
    new_row += " <sos> " + row['translation'] + " <eos> "
    whole_text += new_row

#Fit BPE onto the text.
BPE.fit(whole_text, 4000)
BPE_akk.fit(akkadian_only, 1000)

for k in BPE.vocab.keys():
    print(k, ":", BPE.vocab[k])

#Save the vocabulary and tokens
BPE.save("processed/akk2eng.json")
BPE_akk.save("processed/akkonly.json")

<sos> : 3122
KIŠIB_ : 520
ma_ : 13214
-_ : 129103
nu_ : 2825
ba_ : 2031
lúm_ : 214
a_ : 21141
šur_ : 2063
DUMU_ : 1901
ṣí_ : 609
lá_ : 4466
<god>IM_ : 75
šu_ : 4625
<god>EN.LÍL_ : 79
ki_ : 1638
MAN_ : 24
ta_ : 2937
1/3_ : 750
na_ : 10982
2_ : 1529
GÍN_ : 1860
KÙ.BABBAR_ : 3388
SIG5_ : 324
i_ : 5986
ṣé_ : 445
er_ : 777
PUZUR4_ : 240
hu_ : 993
um_ : 3379
iš_ : 1764
tù_ : 1415
ha_ : 1657
muš_ : 44
tim_ : 1869
ša_ : 6178
ì_ : 269
lí_ : 425
dan_ : 184
ITU.KAM_ : 200
ke_ : 82
li_ : 2367
mu_ : 871
e_ : 1855
sú_ : 1029
in_ : 2534
I TU_ : 4
14_ : 99
am_ : 1898
qal_ : 179
qú_ : 535
ul_ : 435
1/2_ : 1603
GÍN.TA_ : 185
1_ : 1965
im_ : 2730
ITU.1.KAM_ : 79
ib_ : 432
tám_ : 625
ú_ : 3632
ṣa_ : 748
áb_ : 437
<eos> : 3122
Seal_ : 162
of_ : 8815
Mannum_ : 93
balum_ : 28
Aššur_ : 2290
son_ : 1921
Ṣilli_ : 10
Adad,_ : 28
seal_ : 488
Šu_ : 813
Illil_ : 52
kī_ : 73
Aššur,_ : 341
Puzur_ : 360
Ataya._ : 8
Ataya_ : 20
owes_ : 208
22_ : 80
shekels_ : 1520
good_ : 203
silver_ : 2646
to_ : 3951
Ali_ : 599
ahum._ : 61
Reckoned_ : 60
from_ : 1218
the_ : 6506
week_ : 124
Ilī_ : 268
dan,_ : 10
month_ : 135
Ša_ : 19
kēnātim,_ : 7
eponymy_ : 172
Enna_ : 135
Suen,_ : 133
he_ : 1105
will_ : 872
pay_ : 569
weeks._ : 57
If_ : 390
has_ : 561
not_ : 997
paid_ : 406
time,_ : 20
add_ : 134
interest_ : 267
at_ : 1061
rate_ : 104
shekel_ : 408
per_ : 249
mina_ : 986
month._ : 57
TÚG_ : 267
qá_ : 787
tur4_ : 108
DINGIR_ : 344
il5_ : 671
qé_ : 761
Itūr_ : 113
ilī_ : 161
received_ : 148
one_ : 204
textile_ : 108
ordinary_ : 10
quality._ : 7
u_ : 10
la_ : 421
dí_ : 2545
ku_ : 3345
ra_ : 1684
9_ : 137
<big_gap> : 4823
did_ : 106
give_ : 313
you_ : 1782
textile._ : 17
He_ : 232
returned_ : 12
and_ : 4706
bi_ : 1565
lu_ : 1771
mì_ : 1478
bu_ : 1432
wa_ : 974
iq_ : 156
10_ : 827
lim_ : 828
šùr_ : 1252
ut_ : 251
KÙ_ : 52
pì_ : 475
Kūbum,_ : 46
Ṣilū lu_ : 4
U ku._ : 3
When_ : 118
Iddin_ : 396
abum_ : 111
spoke_ : 11
his_ : 696
wil l,_ : 2
gave_ : 568
minas_ : 1503
Šalim_ : 516
Aššur._ : 210
said:_ : 289
may_ : 107
take_ : 234
it_ : 1035
on_ : 413
my_ : 1227
silver._ : 389
tum_ : 591
IŠTAR_ : 705
sí_ : 486
ù_ : 1899
ni_ : 4812
ah_ : 522
šar_ : 114
qí_ : 1158
bi4_ : 1082
áš_ : 983
pu_ : 822
tí_ : 3296
É_ : 326
be_ : 783
ar_ : 635
en_ : 1069
ší_ : 1772
ga_ : 206
<gap> : 859
dì_ : 21
ri_ : 1484
da_ : 1040
kà_ : 2684
zi_ : 587
pí_ : 561
ṭup_ : 813
ṣú_ : 431
ru_ : 1290
an_ : 510
šé_ : 765
<god>UTU_ : 170
tap_ : 63
pá_ : 1121
ub_ : 332
KÙ.GI_ : 116
From_ : 247
Šukkutum_ : 31
Ištar_ : 446
lamassī_ : 35
Ni tah š uš ar:_ : 2
Why_ : 69
is_ : 1090
that_ : 1077
have_ : 842
written_ : 51
me,_ : 111
saying:_ : 94
The_ : 446
house_ : 158
no_ : 97
long er_ : 5
house._ : 65
Urgent,_ : 46
Ennam_ : 817
Do_ : 115
fe ar ! ._ : 1
To_ : 386
lamass ī:_ : 5
are_ : 347
truly_ : 16
sister,_ : 11
then_ : 366
encourage_ : 10
her._ : 12
fe ar._ : 1
A ir_ : 1
textiles_ : 511
I_ : 2065
left._ : 6
Also,_ : 107
tablets_ : 150
should_ : 178
guar ded._ : 2
which_ : 242
Ma ti ?_ : 1
Ti bu la_ : 1
bought_ : 38
do_ : 244
release_ : 51
them_ : 272
anyone_ : 19
before_ : 209
arriv es._ : 4
Šamaš_ : 74
tapp ā ' ī_ : 2
brought_ : 249
Ikūn_ : 127
pīya_ : 62
gold_ : 115
hi_ : 1098
pé_ : 120
za_ : 341
iṣ_ : 136
ih_ : 104
DAM.GÀR_ : 171
iz_ : 96
lim<place>_ : 368
aṣ_ : 88
un_ : 69
nim_ : 966
ik_ : 263
uk_ : 126
ṭá_ : 148
ep_ : 195
me_ : 1693
u4_ : 193
sà_ : 426
Tammuz ī,_ : 3
Elaya,_ : 7
Lamassī_ : 25
ahum:_ : 77
In_ : 209
accordance_ : 155
with_ : 1141
your_ : 990
missive_ : 54
we_ : 645
hired_ : 9
attorney_ : 107
for_ : 1916
Abiya_ : 14
Be be_ : 2
our_ : 456
attorney._ : 23
Take_ : 52
care_ : 94
stand_ : 20
by_ : 1310
very_ : 79
day_ : 96
arrives,_ : 7
assist_ : 38
both_ : 68
regard_ : 8
customers_ : 19
father_ : 174
those_ : 67
whom_ : 28
ar g um ent,_ : 1
first_ : 60
silver,_ : 509
wherever_ : 28
receive_ : 43
it,_ : 44
collect_ : 24
City_ : 297
H all,_ : 5
as_ : 713
much_ : 65
ow es,_ : 5
send_ : 393
together_ : 91
you,_ : 153
so_ : 281
can_ : 148
satisfy_ : 23
epony m._ : 5
comp ound_ : 2
g row_ : 2
too_ : 37
big_ : 6
make_ : 155
unhappy._ : 7
A ct_ : 4
save_ : 11
father's_ : 163
observe_ : 9
there_ : 199
certified_ : 73
de ed s_ : 1
cred its_ : 5
outstanding_ : 70
long_ : 15
term s,_ : 1
tablets,_ : 27
entrust_ : 40
trust wor th y_ : 4
affiliated_ : 39
trader,_ : 10
like_ : 14
yourselves,_ : 6
ext end_ : 1
terms_ : 30
without_ : 37
speci al_ : 1
re as on s,_ : 1
delay_ : 11
but_ : 140
set_ : 97
out_ : 136
come_ : 173
Here_ : 59
seized_ : 155
witnesses_ : 84
against_ : 147
Kūbum_ : 70
Did_ : 8
5_ : 849
tablet ?_ : 2
refused_ : 15
confirm_ : 32
us_ : 322
what_ : 171
dec l are_ : 4
there._ : 42
2/3_ : 421
silver:_ : 39
hire_ : 16
here_ : 149
We_ : 158
16_ : 90
their_ : 188
disposal_ : 7
36_ : 22
expenses,_ : 17
borrowed_ : 21
merchant_ : 80
interest._ : 41
transport_ : 119
back_ : 52
merchant._ : 34
least_ : 33
or_ : 272
store_ : 12
40_ : 138
litres_ : 8
grain_ : 40
come._ : 35
Elaya_ : 6
says:_ : 10
brothers,_ : 95
must_ : 320
proceeds_ : 104
favour._ : 9
el_ : 142
al_ : 616
ti_ : 47
mur_ : 350
ip_ : 214
du_ : 424
13_ : 152
re_ : 96
ak_ : 330
ahum,_ : 86
ilī,_ : 102
Ab il a,_ : 1
Lā_ : 157
qēp,_ : 26
hinnāya_ : 21
had_ : 142
part_ : 9
claim_ : 112
bēl_ : 56
mal k im_ : 1
A t ū ri ya's_ : 1
and from_ : 1
Amur_ : 347
entrusted_ : 157
Elamma_ : 88
amount_ : 35
refined_ : 361
turn_ : 18
ahum_ : 307
this_ : 280
become_ : 29
joint_ : 39
property_ : 7
responsibility_ : 16
hinnāya._ : 10
šál_ : 200
né_ : 188
uš_ : 291
dim_ : 121
ÌR_ : 51
de8_ : 60
30_ : 212
<textile>ku_ : 107
ANŠE_ : 130
úz_ : 53
TÚG.HI.A_ : 178
ANŠE.HI.A_ : 61
kum_ : 294
IGI_ : 1127
GÍR_ : 105
entered_ : 24
Aššur's_ : 188
settle_ : 17
case,_ : 14
While_ : 11
they_ : 459
going_ : 12
lead_ : 34
personally_ : 69
Burušhaddum_ : 27
fe tter s_ : 2
debt_ : 124
slave_ : 94
Abu_ : 85
šalim,_ : 31
other_ : 33
hand_ : 16
black_ : 94
donkey_ : 58
slav e ? Šu_ : 1
Bēlum_ : 178
answered:_ : 141
Yes,_ : 16
taken_ : 74
belongs_ : 30
šalim._ : 17
im pre ssed_ : 4
been_ : 238
sworn_ : 27
City,_ : 60
case_ : 48
does_ : 71
raise_ : 57
slave,_ : 9
then,_ : 7
claims_ : 40
slav e?_ : 2
raises_ : 13
your s,_ : 3
guarantee_ : 6
you._ : 246
Kanesh_ : 151
colony_ : 212
these_ : 162
proceedings,_ : 19
testimony_ : 92
dagger._ : 71
Witnessed_ : 248
Uraya,_ : 9
PÚZUR_ : 27
<god>IŠKUR_ : 32
4_ : 725
17_ : 125
15_ : 424
G ÌN_ : 5
ur_ : 432
A_ : 63
tablet_ : 546
about_ : 196
Assur_ : 128
Adad_ : 97
As anum_ : 3
Al pil i_ : 2
Istar_ : 11
sulu li_ : 4
Ennan at um_ : 1
father,_ : 55
obtained_ : 15
Kuburnat._ : 6
URUDU_ : 577
kam_ : 668
pá t_ : 2
GÚ_ : 387
SÍG.HI.A_ : 70
80_ : 17
Ì.GIŠ_ : 20
dam_ : 98
áp_ : 253
nam_ : 458
price_ : 204
donkey,_ : 12
copper_ : 467
pilah,_ : 12
se ts_ : 4
thi ck_ : 1
saddlecloth s,_ : 4
sik ku_ : 2
bani,_ : 18
jars_ : 25
cum in_ : 1
all_ : 216
available_ : 53
Durhumit._ : 14
pirik an nu_ : 3
textiles,_ : 104
talent_ : 117
wool,_ : 13
sadd le_ : 3
ru g s,_ : 2
po me gr an at es,_ : 1
oli ve_ : 5
oil,_ : 7
sa p tin nu_ : 1
ni br ar u_ : 1
textile,_ : 29
scar f s_ : 2
Zalpa,_ : 9
donkeys_ : 137
harness_ : 35
im it ti ._ : 1
bé_ : 205
num_ : 135
zu_ : 388
ad_ : 109
pirikann u s:_ : 2
Suen_ : 224
pirikannus_ : 8
Akkadian_ : 19
under garmen t,_ : 1
owed_ : 341
Han u_ : 3
pirikann u,_ : 1
Zal pe,_ : 1
ni br ā ru ,_ : 1
Azu_ : 15
ašrannī_ : 19
Ištar._ : 104
All_ : 42
given_ : 68
free_ : 19
loans._ : 7
lam_ : 393
iṭ_ : 18
zal_ : 14
té_ : 345
ag_ : 38
us,_ : 22
said_ : 85
Aššur:_ : 219
L end_ : 1
talents_ : 264
wa she d,_ : 4
broken_ : 9
copper,_ : 81
re im bur se_ : 2
lent_ : 5
Within_ : 13
days_ : 31
shall_ : 370
copper._ : 58
What_ : 16
if_ : 142
indeed_ : 26
15 th_ : 1
exceeded_ : 6
all ?_ : 1
Let_ : 84
As_ : 195
interest,_ : 15
term_ : 37
ob li ga tion._ : 1
god_ : 14
ri se_ : 1
ṣulūlī_ : 13
Kuzallu,_ : 8
Ṣilū lu._ : 4
continu ed_ : 1
say ing_ : 5
arrive_ : 23
P urušhadd um,_ : 4
ear n ings_ : 3
thus_ : 75
favour_ : 14
mysel f._ : 3
Wahšušana_ : 34
proceedings_ : 58
idī,_ : 15
Elāli_ : 20
Bal zu en um_ : 1
was_ : 322
absent_ : 27
partner._ : 26
le_ : 145
tal_ : 92
sá_ : 91
gu5_ : 43
urgent,_ : 9
clear_ : 82
yourselves_ : 13
any_ : 77
B urušhadd um !_ : 1
Sell_ : 20
even_ : 34
girls_ : 10
price,_ : 7
come!_ : 9
previou s ly_ : 3
ple ad ed_ : 3
fin an ci ers_ : 1
agree_ : 7
today_ : 21
agre ed!_ : 1
9 2_ : 3
<textile>a_ : 11
ŠU.NÍGIN_ : 97
TÚG.HI_ : 32
ŠÀ_ : 9
<textile> bu_ : 4
27_ : 24
5/6_ : 188
AN.NA_ : 490
7_ : 302
<textile> kam_ : 1
ir_ : 442
11_ : 125
6_ : 374
50_ : 79
20_ : 248
3_ : 947
kur_ : 70
n_ : 8
abum,_ : 63
Inah_ : 23
You_ : 149
x ,_ : 2
further,_ : 44
Abarnian_ : 15
credit_ : 17
wrote_ : 113
total_ : 10
textiles:_ : 15
h und red_ : 2
thereof_ : 47
rob es,_ : 2
tin_ : 394
100_ : 28
either_ : 58
fine_ : 49
apart_ : 31
import_ : 79
dut y,_ : 1
wrapping_ : 12
Kurub_ : 52
sealed_ : 117
died_ : 13
during_ : 15
journey,_ : 6
32_ : 17
23_ : 37
left_ : 186
supp ort_ : 3
goods._ : 32
bou ght._ : 3
Of_ : 95
For_ : 93
rest_ : 103
6 00_ : 4
nail s_ : 4
8 6_ : 5
gre en_ : 2
ones_ : 8
wool_ : 68
8_ : 288
24_ : 61
each._ : 8
eye_ : 10
20 +_ : 2
under_ : 309
when_ : 180
relea se d,_ : 1
now ,_ : 3
12_ : 250
the irs_ : 1
2 7 !_ : 1
rob es_ : 5
tin,_ : 90
57_ : 8
Dadaya_ : 10
Qa q q ad ānum_ : 1
48_ : 20
Uzuwa_ : 10
I k ra_ : 1
tin:_ : 7
lik_ : 198
SA .TU_ : 1
uq_ : 118
uz_ : 15
pè_ : 110
malik_ : 79
abum:_ : 7
bāni,_ : 100
šadu'e_ : 6
purchases_ : 42
City._ : 93
Se ttle_ : 4
affair_ : 27
well_ : 38
word_ : 95
him._ : 103
My_ : 224
dear_ : 228
inform_ : 33
way_ : 35
whether_ : 37
settled._ : 6
care ._ : 2
dur4_ : 38
U M _ : 1
pa_ : 4
ṭur4_ : 28
<big_gap> Akkadian_ : 1
seal,_ : 49
bēlī_ : 16
pilah_ : 14
bring_ : 180
pl ur al ._ : 2
a._ : 6
They_ : 99
smugg l ing._ : 1
count_ : 5
ahum's_ : 21
Uku_ : 18
him_ : 463
brings_ : 96
seal._ : 85
wan ts_ : 4
there,_ : 47
buy_ : 54
donkey._ : 9
small_ : 49
Give_ : 71
plus_ : 74
donkey 's_ : 1
p li ah_ : 1
pack_ : 11
textiles._ : 47
sacks_ : 60
Nah ur_ : 1
ch i se l_ : 3
let_ : 300
E lu h ut_ : 1
ili5_ : 84
qar_ : 43
imittī_ : 66
lu ṣ u,_ : 1
šalim_ : 58
emūq ī._ : 4
concerning_ : 192
bāni_ : 216
Ahu_ : 36
waqar_ : 24
dagger_ : 43
lu ṣ u_ : 1
emūqī_ : 9
heard_ : 48
statement._ : 17
ŠÀ.BA_ : 127
18_ : 74
Lad iya,_ : 1
L ila_ : 3
reached_ : 19
agreement_ : 25
investors,_ : 13
satisfied_ : 17
investors_ : 77
possession._ : 34
Thereof ,_ : 2
share s,_ : 3
Iliya,_ : 22
its_ : 247
value_ : 25
Apart_ : 9
nothing_ : 18
them._ : 53
Our_ : 25
lords,_ : 31
also,_ : 27
wor d,_ : 5
great_ : 14
many_ : 14
creditors_ : 6
who_ : 134
remain._ : 13
passed_ : 29
verdict_ : 49
stating_ : 51
men tion_ : 5
sons_ : 67
how_ : 35
cover_ : 18
abum's_ : 24
debt._ : 25
say:_ : 16
This_ : 24
differ ent_ : 4
pla c es._ : 2
6 6_ : 3
maš_ : 25
25_ : 80
ùh_ : 55
u g_ : 5
19_ : 20
fleec es,_ : 2
harness,_ : 12
second_ : 22
transport._ : 26
id_ : 253
wardī_ : 47
Nūn u._ : 2
idī_ : 30
M u_ : 1
mu l ānum,_ : 1
taklāku_ : 40
Ikūnum_ : 15
Sama ya._ : 3
DINGIR. SIPA_ : 3
nādā_ : 56
imittī,_ : 42
Išme_ : 12
ilum,_ : 20
B i_ : 1
han n ān iya,_ : 1
rē'ī_ : 17
Š ak ṣ um._ : 1
qúl_ : 147
creditor._ : 19
Con trac ted_ : 1
X II ._ : 2
within_ : 101
Y e ar_ : 2
nādā,_ : 38
successor_ : 16
Karwa ya._ : 3
DU10_ : 247
B ub urānum_ : 2
ṭāb_ : 83
specifically_ : 49
ṭāb:_ : 10
B ad iya_ : 1
li ved_ : 3
since_ : 41
Nar ma k_ : 3
just_ : 9
kept_ : 17
sil ent._ : 1
over_ : 49
caravan_ : 63
fe es._ : 2
refuses_ : 12
come,_ : 19
im por tan t_ : 2
cheat_ : 12
B ind_ : 1
brough t._ : 5
acquired_ : 9
myself_ : 35
sent_ : 191
Ennānum_ : 66
Kuziya_ : 6
brother,_ : 129
attention_ : 31
missives_ : 13
answer_ : 18
express_ : 13
it._ : 96
leave_ : 54
travell ers_ : 4
depar t._ : 2
31_ : 26
šad ū ' e,_ : 1
šarrassa_ : 11
instructions_ : 43
led_ : 20
into_ : 46
hear t lan d,_ : 1
Thereof_ : 21
deposited_ : 54
tarif f._ : 2
seals._ : 28
disposal ._ : 5
With_ : 35
respect_ : 41
promised_ : 38
us._ : 31
After_ : 25
came_ : 43
g one._ : 1
Because_ : 6
made_ : 97
wait_ : 6
day s._ : 5
arrives_ : 22
final_ : 11
report_ : 16
ši_ : 80
Kuliya,_ : 43
say,_ : 12
says_ : 16
As ān um:_ : 3
still_ : 47
staying_ : 29
because_ : 42
meteoric_ : 13
iron._ : 6
quality_ : 49
iron_ : 39
sell_ : 63
get_ : 42
ready_ : 21
letter_ : 72
arrived_ : 29
a x e,_ : 1
yet_ : 24
re cord ed_ : 3
dispos iti ons_ : 3
witnesses._ : 25
A mong_ : 3
fi gu res_ : 1
Azu,_ : 6
transporter_ : 7
Please,_ : 38
lord,_ : 29
approach_ : 13
tes ti fy_ : 1
colleagu es._ : 2
whi th out_ : 1
know le dge_ : 3
Elā l ī._ : 2
dum_ : 41
Damiq_ : 61
pī_ : 105
Šāt_ : 26
Anna:_ : 6
purchases._ : 20
Three_ : 6
times_ : 16
wa ited_ : 2
road_ : 24
Pay_ : 34
goods_ : 156
aq_ : 42
carry_ : 14
purchase_ : 22
yourself_ : 22
Ah ātum_ : 3
abum._ : 41
gul_ : 3
eš_ : 45
left,_ : 13
du gul_ : 4
took_ : 139
Zik ur_ : 3
were_ : 115
account_ : 23
kutān u._ : 1
U m_ : 1
took._ : 14
qám_ : 22
46_ : 23
Elāli,_ : 7
Dan_ : 48
Pūšu_ : 37
kēn_ : 22
Su ey ya._ : 2
stock_ : 31
investment_ : 17
tablet,_ : 45
belonging_ : 185
write_ : 55
down_ : 56
name_ : 79
investor s._ : 5
him,_ : 27
4 0 ?_ : 2
representing_ : 9
gold,_ : 21
weeks_ : 29
reckoned_ : 15
Ikūnum,_ : 8
enter_ : 24
favour able_ : 2
refu se d,_ : 1
kēn._ : 10
memorandum_ : 11
copy_ : 13
KÙ.KI_ : 32
az_ : 38
lam x_ : 1
mar_ : 21
Say_ : 61
Atata_ : 16
Kannutum,_ : 6
Anah_ : 29
ili :_ : 1
Ili_ : 27
caused_ : 7
trouble_ : 8
expenses_ : 49
now_ : 31
dr ag ged_ : 1
responsible_ : 15
Kannu t um's_ : 1
interes ts._ : 1
Should_ : 15
Kannu tum_ : 2
ili,_ : 8
a fo re mentioned_ : 1
O f fice_ : 1
ban i 's_ : 2
deb ts._ : 2
Over_ : 7
ordered_ : 10
bani_ : 21
available,_ : 12
seize_ : 32
pa s allum_ : 1
own_ : 82
responsibility._ : 6
strong_ : 13
belong_ : 17
Kannu tum._ : 1
And_ : 57
Kuliya_ : 29
comes_ : 21
order_ : 30
affair ,_ : 3
hold_ : 45
pla y_ : 1
until_ : 108
arrive,_ : 8
affair !_ : 1
ṣur_ : 33
Dudiki,_ : 7
Uṣur_ : 67
Aku wa,_ : 2
do g ._ : 1
temple_ : 13
funds_ : 12
behalf_ : 47
0_ : 67
KI_ : 178
working_ : 88
capital_ : 87
Amriya_ : 8
mina:_ : 6
awātim_ : 14
GAL_ : 88
M AN. IŠTAR_ : 3
E ra se_ : 1
me._ : 191
meet_ : 13
Istar,_ : 13
DIRI_ : 88
bí_ : 23
ILLAT_ : 59
kál_ : 85
excise_ : 42
added,_ : 70
fee_ : 36
paid,_ : 59
seals,_ : 31
representatives_ : 92
En tru sted_ : 1
presence_ : 132
Šamaš,_ : 23
Mī šar_ : 4
rabi,_ : 19
har im tum._ : 1
hinnāya,_ : 15
Ummī_ : 20
Išhara_ : 16
Lamassutum_ : 13
Aššuriš_ : 45
tikal,_ : 15
35_ : 40
being_ : 22
this,_ : 21
representatives._ : 27
Izzizam_ : 6
nādā._ : 9
t í m_ : 1
Come,_ : 14
question_ : 12
you!_ : 8
want_ : 9
me?_ : 19
Ab out_ : 5
memoranda_ : 14
settled_ : 49
accoun ts._ : 5
Con test_ : 1
y es,_ : 2
con test_ : 5
Keep_ : 13
mind_ : 12
City!_ : 7
Bring_ : 9
assembly_ : 54
lord._ : 16
rabi_ : 34
eb_ : 20
Kuziz ya_ : 2
message_ : 46
Pilah_ : 97
acc ess_ : 4
room_ : 13
container_ : 20
Alula ya._ : 1
harnessor_ : 8
some wher e,_ : 2
placed_ : 30
Alulaya_ : 19
Ewarimuša_ : 11
instruc ted,_ : 2
Purušhaddum._ : 11
lad y._ : 4
So,_ : 8
word._ : 12
wrote,_ : 7
it!_ : 13
kutānus_ : 12
votive_ : 39
offer ing s:_ : 1
sold_ : 72
ch ief_ : 5
mu les_ : 1
Kuziziya_ : 27
Your_ : 53
M ari th um,_ : 3
thin_ : 36
available._ : 18
trad e_ : 3
stil l._ : 1
best_ : 7
gold._ : 13
C er ti fied_ : 2
e z_ : 3
ṭù_ : 69
Aš du_ : 2
weighed_ : 8
weight_ : 21
Enah_ : 28
B o th_ : 4
split_ : 8
en ve lo p e_ : 3
again_ : 12
nimr ī._ : 1
realise_ : 7
every_ : 57
et_ : 48
wi_ : 139
Sad ly,_ : 3
died._ : 10
mo ur ning_ : 3
assets_ : 17
There_ : 24
wil l._ : 2
death_ : 6
men_ : 56
agreed_ : 21
earlier_ : 19
turned_ : 9
NINDA_ : 36
up_ : 153
b ent_ : 1
doing_ : 4
treated_ : 11
bad ly_ : 2
lord_ : 8
con s um ing_ : 1
bread ._ : 3
instructed_ : 15
'You_ : 7
girl_ : 34
son ! ',_ : 1
reason_ : 14
her_ : 115
son._ : 13
Send_ : 94
native_ : 8
representative._ : 6
UDU.HI.A_ : 8
Al ili_ : 5
Kar šin i_ : 4
owe_ : 98
Waldi_ : 14
ilum_ : 30
lamassī._ : 14
sheep_ : 16
fe a st_ : 1
Tuh tu h ānum._ : 1
Before_ : 22
Kar n ik aš u._ : 1
<god>IM.GAL_ : 11
G UDU 4_ : 4
ig_ : 66
wu_ : 32
GÁN_ : 24
KÁ_ : 7
q_ : 2
rabi :_ : 4
asked_ : 17
Issu_ : 58
arik_ : 29
cleared_ : 33
affairs_ : 8
M er ani,_ : 2
pri est_ : 5
Z ak ta ya's_ : 1
firm,_ : 8
where_ : 68
lo an,_ : 5
time_ : 26
could_ : 14
certify_ : 10
guarant or ?_ : 1
No_ : 7
certi fi ed._ : 1
men._ : 9
continued:_ : 10
It_ : 56
tru e_ : 5
discu ssed_ : 2
' Pay_ : 2
ab ro ad,_ : 2
go_ : 131
brother's_ : 14
capital .'_ : 1
words_ : 40
of f,_ : 2
statement_ : 10
Gate_ : 31
God._ : 13
share,_ : 10
opened_ : 17
Bēl ā t um's_ : 1
house,_ : 42
only_ : 24
single_ : 67
concer ned_ : 1
U ku wa_ : 1
partners._ : 7
presen t._ : 4
Ennān um's_ : 5
sear ched_ : 4
ren d ered_ : 4
sa c red_ : 4
pre c in ct_ : 3
Ibaya's_ : 10
son,_ : 20
whoever_ : 6
extrad iti on_ : 3
ab road_ : 2
invalid._ : 10
ren der_ : 4
man_ : 85
makes_ : 6
formal_ : 10
inv o l ving_ : 1
deposit i on,_ : 1
re ve al_ : 1
colony,_ : 27
concer ns_ : 5
three_ : 26
inv o l ve_ : 1
any way_ : 1
li ve._ : 1
grain._ : 10
S pe ak_ : 1
sto red._ : 2
N ow_ : 5
pre ss ure_ : 2
grain,_ : 11
loan s,_ : 3
the y ?_ : 1
someone_ : 10
away_ : 31
last_ : 10
five_ : 18
years_ : 21
un willing_ : 4
foll ow_ : 1
order s._ : 5
angr y ?_ : 1
lo ans_ : 4
quarre l_ : 4
tre at_ : 2
har sh ly_ : 2
to day!_ : 2
mysel f :_ : 2
in sul ting_ : 1
him ?_ : 3
huraṣānum_ : 6
offered_ : 12
dispose_ : 10
s im il ar_ : 1
So_ : 7
mone y!_ : 1
en6_ : 45
LÁ_ : 63
šum_ : 50
tu_ : 7
kúl_ : 7
dark_ : 32
Burušhattum_ : 7
deducted_ : 26
equivalent_ : 6
Kūbum's_ : 7
account._ : 20
shekels._ : 37
Thereof:_ : 14
28_ : 20
Tum e liya._ : 1
fodder_ : 14
Wahšušana,_ : 8
transported_ : 20
Ulama_ : 9
cost_ : 58
in n._ : 4
ha biya_ : 1
wife_ : 56
ab_ : 30
É.GAL_ : 50
S ave_ : 2
while_ : 19
saved._ : 6
two_ : 89
journey_ : 29
lapis_ : 63
lazuli_ : 38
see_ : 22
Anatoli an s,_ : 1
se en_ : 4
lazuli._ : 8
convert_ : 10
some_ : 56
lazuli,_ : 13
palace_ : 35
gate_ : 10
here._ : 84
others_ : 8
Sealed_ : 33
ṭ ab ._ : 1
Abi ya._ : 5
care!_ : 7
PUZUR4. SA .TU_ : 3
lum_ : 9
56_ : 14
Ištar,_ : 166
letter,_ : 20
matter_ : 64
cor re ct_ : 4
letter._ : 7
raised_ : 6
lawsuit_ : 12
God_ : 13
tablet._ : 66
Ah um_ : 3
šadu' e 's_ : 2
extrad ite_ : 6
ow n er_ : 4
capital._ : 15
mer h can t_ : 1
1 56_ : 2
harness or s:_ : 1
each_ : 49
capital s_ : 5
clothes_ : 13
less_ : 37
tariff_ : 60
export_ : 11
duty_ : 53
all:_ : 20
leads_ : 10
5 +_ : 1
leave._ : 14
Kuk a wa,_ : 1
Adida_ : 37
On ce_ : 5
twice_ : 19
de al_ : 5
safe_ : 16
m ann er._ : 2
keep_ : 64
writing_ : 14
bringing_ : 45
Narrow_ : 15
Trac k._ : 4
wro te :_ : 4
D ec ide_ : 1
safe ty_ : 3
good s!_ : 1
H ow ever ,_ : 4
orders_ : 17
p al ac es,_ : 1
them,_ : 10
str ic t,_ : 3
com m on_ : 2
cau se._ : 1
Azuz aya's_ : 2
n ar row_ : 4
trac k_ : 2
detained_ : 7
day._ : 9
twi ce,_ : 5
fathers,_ : 7
sa ving_ : 1
dispatch_ : 9
delayed_ : 16
inde ed,_ : 2
why_ : 17
hav e <big_gap>_ : 1
4 9_ : 6
52_ : 7
ap_ : 21
Il uwa_ : 1
Su ey ya:_ : 1
Būr_ : 17
Zuba_ : 9
including_ : 34
the,_ : 10
huraṣ ānum._ : 3
smuggling_ : 8
fe e._ : 2
En trust_ : 4
seal ings_ : 3
he m s._ : 1
Concerning_ : 64
lost_ : 13
Elā li._ : 4
na.TA_ : 47
kutānu_ : 23
+_ : 11
pie ce_ : 6
Irnu id._ : 1
Aluwa_ : 54
Con ver t_ : 3
c an._ : 4
ṭí_ : 81
Zukuwa_ : 14
profitable_ : 12
travell ers._ : 2
Damqaya_ : 8
deduc tions_ : 3
firm_ : 5
Ababa_ : 17
According_ : 9
behind_ : 19
show_ : 23
ou standing_ : 2
anything_ : 37
behin d,_ : 4
Yesterday_ : 7
questioned_ : 28
whatever_ : 18
City !'_ : 2
brother_ : 121
' Come,_ : 1
City .'_ : 5
But_ : 26
gi ving_ : 6
harsh_ : 8
answer s_ : 4
instead_ : 10
pa ying_ : 3
refuse_ : 9
obstruct_ : 23
are !_ : 2
sh ow s_ : 1
Come_ : 25
along_ : 16
now !_ : 1
me!_ : 15
answered_ : 36
Abab a:_ : 4
submit_ : 12
' At_ : 2
Durhumit_ : 38
assisted_ : 7
father._ : 26
appro pri ated_ : 3
things_ : 13
il leg ally_ : 2
tablet .'_ : 2
are ,_ : 5
eponym_ : 17
discuss_ : 15
testament_ : 10
sister ._ : 4
'I_ : 14
Durhum it !'_ : 1
state_ : 7
to day._ : 2
cour t._ : 6
re jec ted_ : 4
go ing!_ : 1
Ababa,_ : 8
'Come_ : 7
along !_ : 2
to day,_ : 3
claims,_ : 13
tikal_ : 31
booked_ : 20
office_ : 31
colon y:_ : 3
bad_ : 21
hu ma_ : 3
Annina_ : 27
recie ved_ : 6
copper:_ : 9
colony._ : 50
T an a wi š ti_ : 1
Išta ku šar :_ : 2
f led_ : 1
Seize_ : 23
loan_ : 14
con tests_ : 3

### Encode Text into tokens
WARNING. THIS CELL TAKES VERY LONG TO EXECUTE (~11 Hours). Be warned.

NOTE: The same operations in this notebook is copied onto compiled/preprocess.py. This can be more easily executed in a cloud server if you have one.

In [ ]:
for i, row in cleaned_complete_df.iterrows():
    new_row = " <sos> " + row['transliteration'] + " <eos> "
    encoded = BPE.encode(new_row)
    cleaned_complete_df.at[i, 'transliteration'] = encoded

    new_row = " <sos> " + row['translation'] + " <eos> "
    encoded = BPE.encode(new_row)
    cleaned_complete_df.at[i, 'translation'] = encoded

for i, row in cleaned_incomplete_df.iterrows():
    new_row = " <sos> " + row['transliteration'] + " <eos> "
    encoded = BPE.encode(new_row)
    cleaned_incomplete_df.at[i, 'transliteration'] = encoded

    new_row = " <sos> " + row['translation'] + " <eos> "
    encoded = BPE.encode(new_row)
    cleaned_incomplete_df.at[i, 'translation'] = encoded

['<sos>', 'KIŠIB_', 'ma', '-', 'nu', '-', 'b', 'a', '-', 'l', 'ú', 'm', '-', 'a', '-', 'šur_', 'DUMU_', 'ṣ', 'í', '-', 'lá', '-_', '<god>', 'IM_', 'KIŠIB_', 'š', 'u', '-_', '<god>', 'EN.LÍL_', 'DUMU_', 'ma', '-', 'nu', '-', 'ki', '-', 'a', '-', 'šur_', 'KIŠIB_', 'M', 'AN', '-', 'a', '-', 'šur_', 'DUMU_', 'a', '-', 'ta', '-', 'a_', '1/3_', 'ma', '-', 'na_', '2_', 'GÍN_', 'KÙ.BABBAR_', 'SIG5_', 'i', '-', 'ṣ', 'é', '-', 'er_', 'PUZUR', '4', '-', 'a', '-', 'šur_', 'DUMU_', 'a', '-', 'ta', '-', 'a', '-', 'lá', '-', 'hu', '-', 'um_', 'i', '-', 'šu_', 'iš', '-', 'tù_', 'ha', '-', 'mu', 'š', '-', 'tim_', 'ša_', 'ì', '-', 'l', 'í', '-', 'dan_', 'ITU.KAM_', 'ša_', 'ke', '-', 'na', '-', 'tim_', 'li', '-', 'mu', '-', 'um_', 'e', '-', 'na', '-', 's', 'ú', '-', 'in_', 'a', '-', 'na_', 'I', 'TU_', '14_', 'ha', '-', 'am', '-', 'š', 'a', '-', 'tim_', 'i', '-', 'š', 'a', '-', 'qal_', 'š', 'u', '-', 'ma_', 'lá_', 'iš', '-', 'q', 'ú', '-', 'ul_', '1/2_', 'GÍN.TA_', 'a', '-', 'na_', '1_', 'ma', '-', 'na', '-', 'im_', 'i', '-', 'na_', 'ITU.1.KAM_', 'ṣ', 'í', '-', 'ib', '-', 'tám_', 'ú', '-', 'ṣ', 'a', '-', 'áb_', '<eos>']
['<sos>', '1_', 'TÚG_', 'ša_', 'q', 'á', '-', 'tim_', 'i', '-', 'tur', '4', '-', 'DINGIR_', 'il', '5', '-', 'qé_', '<eos>']
['<sos>', 'TÚG_', 'u', '-', 'la_', 'i', '-', 'd', 'í', '-', 'na', '-', 'ku', '-', 'um_', 'i', '-', 't', 'ù', '-', 'ra', '-', 'ma_', '9_', 'GÍN_', 'KÙ.BABBAR_', '<eos>']
['<sos>', 'KIŠIB_', 'š', 'u', '-_', '<god>', 'EN.LÍL_', 'DUMU_', 'š', 'u', '-', 'ku', '-', 'bi', '-', 'im_', 'KIŠIB_', 'ṣ', 'í', '-', 'lu', '-', 'lu_', 'DUMU_', 'ú', '-', 'ku_', 'i', '-', 'nu', '-', 'mì_', 'i', '-', 'd', 'í', '-', 'a', '-', 'bu', '-', 'um_', 'a', '-', 'wa', '-', 'sú_', 'i', 'q', '-', 'bi', '-', 'ú_', '10_', 'ma', '-', 'na_', 'KÙ.BABBAR_', 'a', '-', 'na_', 'š', 'a', '-', 'li', 'm', '-', 'a', '-', 'šùr_', 'i', '-', 'd', 'í', '-', 'in_', 'um', '-', 'ma_', 'š', 'u', '-', 'u', 't', '-', 'ma_', 'i', '-', 'ṣ', 'í', '-', 'b', 'a', '-', 'at_', 'KÙ', '-', 'p', 'ì', '-', 'a_', 'li', '-', 'il', '5', '-', 'qé_', '<eos>']
['<sos>', 'um', '-', 'ma_', 'š', 'u', '-', 'ku', '-', 't', 'um', '-', 'ma_', 'a', '-', 'na_', 'IŠT', 'A', 'R', '-', 'lá', '-', 'ma', '-', 'sí_', 'ù_', 'ni', '-', 'ta', '-', 'ah', '-', 'š', 'u', '-', 'šar_', 'q', 'í', '-', 'bi', '4', '-', 'ma_', 'm', 'ì', '-', 'šu_', 'ša_', 'ta', '-', 'á', 'š', '-', 'p', 'u', '-', 'ra', '-', 'ni', '-', 'ni_', 'um', '-', 'ma_', 'a', '-', 't', 'í', '-', 'na', '-', 'ma_', 'É', '-', 'tum_', 'a', '-', 'na_', 'lá_', 'be', '-', 'tim_', 'i', '-', 't', 'ù', '-', 'ar_', 'a', '-', 'p', 'u', '-', 'tum_', 'a', '-', 'na_', 'en', '-', 'um', '-', 'a', '-', 'šùr_', 'i', '-_', '<big_gap>', '-', 'ni', '-', 'ma_', 'e_', 'š', 'í', '-', 'na_', 'ga_', '<gap>', 'ša_', 'lá_', 'ta', '-', 'ha', '-', 'd', 'ì', '-', 'ri_', 'a', '-', 'na_', 'IŠT', 'A', 'R', '-', 'lá', '-', 'ma', '-', 'sí_', 'q', 'í', '-', 'bi', '4', '-', 'ma_', 'š', 'u', '-', 'ma_', 'a', '-', 'ha', '-', 'tí_', 'a', '-', 'ta_', 'li', '-', 'b', 'a', '-', 'am_', 'd', 'ì', '-', 'ni', '-', 'š', 'í', '-', 'im_', 'lá_', 'ta', '-', 'ha', '-', 'da', '-', 'ar_', 'a', '-', 'na_', 'ni', '-', 'ta', '-', 'ah', '-', 'š', 'u', '-', 'šar_', 'q', 'í', '-', 'bi', '4', '-', 'ma_', 'TÚG', '-', 'p', 'ì', '-', 'ri', '-', 'k', 'à', '-', 'ni_', 'ša_', 'e', '-', 'z', 'i', '-', 'bu_', 'na', '-', 'p', 'í', '-', 'š', 'í', '-', 'š', 'u', '-', 'nu_', 'ù_', 'ṭ', 'up', '-', 'p', 'u', '-', 'ú_', 'lu_', 'š', 'a', '-', 'ṣ', 'ú', '-', 'ru_', 'p', 'ì', '-', 'ri', '-', 'k', 'à', '-', 'nu_', 'ša_', 'ma', '-', 'tí_', 'ù_', 't', 'í', '-', 'bu', '-', 'lá_', 'ma', '-', 'a', '-_', '<gap>', 'iš', '-', 'ta', '-', 'ú', '-', 'mu', '-', 'ni_', 'a', '-', 'dí_', 'en', '-', 'um', '-', 'a', '-', 'šùr_', 'i', '-', 'lá', '-', 'k', 'à', '-', 'ni_', 'a_', 'ma', '-', 'ma', '-', 'an_', 'lá_', 't', 'ù', '-', 'š', 'é', '-', 'ri_', '<gap>', 'GÍN_', 'KÙ.BABBAR_', '<god>', 'U', 'T', 'U', '-', 'ta', 'p', '-', 'pá', '-', 'i_', 'ub', '-', 'lá', '-', 'ki', '-', 'im_', '1_', 'GÍN_', 'KÙ.GI_', 'ù_', '<gap>', 'GÍN_', 'KÙ.BABBAR_', 'i', '-', 'ku', '-', 'p', 'ì', '-', 'a_', 'ub', '-', 'lá', '-', 'ki', '-', 'im_', '<eos>']
['<sos>', 'um', '-', 'ma_', 'š', 'u', '-', 'ta', '-', 'mu', '-', 'zi_', 'e', '-', 'lá', '-', 'a_', 'en', '-', 'um', '-', 'a', '-', 'šùr_', 'ù_', 'lá', '-', 'ma', '-', 's', 'í', '-', 'ma_', 'a', '-', 'na_', 'en', '-', 'um', '-', 'a', '-', 'šùr_', 'ù_', 'a', '-', 'lá', '-', 'hi', '-', 'im_', 'q', 'í', '-', 'bi', '4', '-', 'ma_', 'a', '-', 'ma', '-', 'la_', 'na', '-', 'á', 'š', '-', 'p', 'é', '-', 'er', '-', 't', 'í', '-', 'ku', '-', 'nu_', 'ra', '-', 'bi', '-', 'ṣ', 'a', '-', 'am_', 'ni', '-', 'hu', '-', 'z', 'a', '-', 'ku', '-', 'nu', '-', 'tí_', 'a', '-', 'bi', '-', 'a_', 'DUMU_', 'be', '-', 'e', '-', 'be_', 'ra', '-', 'bi', '4', '-', 'i', 'ṣ', '-', 'ni_', 'i', '-', 'na_', 'š', 'a', '-', 'am', '-', 'ší_', 'ša_', 'ra', '-', 'bi', '-', 'ṣ', 'ú', '-', 'um_', 'e', '-', 'ra', '-', 'b', 'a', '-', 'ni_', 'i', 'h', '-', 'da', '-', 'ma_', 'i', '-', 'z', 'i', '-', 'z', 'a', '-', 'ma_', 'lu_', 'DAM.GÀR_', 'a', '-', 'bi', '-', 'ku', '-', 'nu_', 'lu_', 'ša_', 'a', '-', 'wa', '-', 'tám_', 't', 'í', '-', 'š', 'u', '-', 'a', '-', 'ni_', 'ra', '-', 'bi', '-', 'ṣ', 'ú', '-', 'um_', 'i', '-', 'na_', 'š', 'a', '-', 'ha', '-', 't', 'í', '-', 'ku', '-', 'nu_', 'li', '-', 'z', 'i', '-', 'iz', '-', 'ma_', 'i', '-', 'na_', 'KÙ.BABBAR_', 'pá', '-', 'ni', '-', 'ma_', 'a', '-', 'šar_', 'ta', '-', 'ma', '-', 'ha', '-', 'ra', '-', 'ni_', 'KÙ.BABBAR_', 'ša_', 'É_', 'a', '-', 'lim_', '<place>', 'š', 'u', '-', 'ta', '-', 'a', 'ṣ', '-', 'bi', '-', 'ta', '-', 'ma', '-', 'lá_', 'a', '-', 'bu', '-', 'ku', '-', 'nu_', 'ha', '-', 'bu', '-', 'lu_', 'KÙ.BABBAR_', 'ku', '-', 'un', '-', 'k', 'à', '-', 'ma_', 'š', 'é', '-', 'bi', '-', 'lá', '-', 'nim_', 'ra', '-', 'bi', '4', '-', 'ṣ', 'ú', '-', 'um_', 'iš', '-', 't', 'í', '-', 'ku', '-', 'nu_', 'li', '-', 'ik', '-', 'nu', '-', 'u', 'k', '-', 'ma_', 'KÙ.BABBAR_', 'š', 'é', '-', 'bi', '-', 'lá', '-', 'nim', '-', 'ma_', 'li', '-', 'ma', '-', 'am_', 'lu_', 'nu', '-', 'š', 'a', '-', 'bi_', 'ṣ', 'í', '-', 'b', 'a', '-', 'at_', 'ṣ', 'í', '-', 'ib', '-', 'tim_', 'lá_', 'i', '-', 'ma', '-', 'i', '-', 'da', '-', 'ku', '-', 'nu', '-', 't', 'í', '-', 'ma_', 'li', '-', 'b', 'a', '-', 'ku', '-', 'nu_', 'e_', 'im', '-', 'ra', '-', 'aṣ_', 'ma', '-', 'lá_', 'e', '-', 'ṭ', 'á', '-', 'ar_', 'É_', 'a', '-', 'bi', '4', '-', 'ku', '-', 'nu_', 'ep', '-', 'ša_', 'š', 'u', '-', 'ma_', 'ta', '-', 'da', '-', 'ga', '-', 'lá', '-', 'ma_', 'ṭ', 'up', '-', 'pu_', 'ha', '-', 'ru', '-', 'mu', '-', 'tum_', 'ú_', 'b', 'a', '-', 'b', 'a', '-', 'a', '-', 'tum_', 'ru', '-', 'q', 'á', '-', 'tum_', 'i', '-', 'b', 'a', '-', 'š', 'í', '-', 'ú_', 'ṭ', 'up', '-', 'pí_', 'ku', '-', 'un', '-', 'k', 'à', '-', 'ma_', 'a', '-', 'na_', 'DUMU_', 'um', '-', 'me', '-', 'a', '-', 'nim_', 'ke', '-', 'nim_', 'ša_', 'ki', '-', 'ma_', 'ku', '-', 'nu', '-', 'tí_', 'p', 'í', '-', 'i', 'q', '-', 'da', '-', 'ma_', 'u', '4', '-', 'me', '-', 'e', '-', 'ku', '-', 'nu_', 'b', 'a', '-', 'lu', '-', 'um_', 'm', 'ì', '-', 'ma', '-', 'ma_', 'lá_', 't', 'ù', '-', 'ri', '-', 'q', 'á', '-', 'ma_', 'lá_', 'ta', '-', 's', 'à', '-', 'hu', '-', 'ra_', 'iš', '-', 'tí_', 'ra_', '<eos>']
['<sos>', 'KIŠIB_', 'a', '-', 'lá', '-', 'hi', '-', 'im_', 'KIŠIB_', 'a', '-', 'li', '-', 'li_', 'KIŠIB_', 'a', '-', 'bi', '4', '-', 'lá_', 'KIŠIB_', 'lá', '-', 'q', 'é', '-', 'ep_', 'ša_', 'i', '-', 'na_', 'b', 'a', '-', 'á', 'b', '-', 'tim_', 'ša_', 'a', '-', 'šù', 'r', '-', 'be', '-', 'el', '-', 'ma', '-', 'al', '-', 'ki', '-', 'im_', 'ša_', 'iš', '-', 'ti_', 'DUMU_', 'a', '-', 't', 'ù', '-', 'ri', '-', 'a_', 'ù_', 'a', '-', 'm', 'ur', '-', 'a', '-', 'šùr_', 'hi', '-', 'na', '-', 'a_', 'i', 'ṣ', '-', 'bu', '-', 't', 'ù', '-', 'ma_', 'a', '-', 'na_', 'e', '-', 'lá', '-', 'ma_', 'ip', '-', 'q', 'í', '-', 'du_', '2_', 'ma', '-', 'na_', '13_', '1/2_', 'GÍN_', 'KÙ.BABBAR_', 'ṣ', 'a', '-', 'ru', '-', 'pá', '-', 'am_', 'e', '-', 'lá', '-', 'ma_', 'a', '-', 'na_', 'a', '-', 'lá', '-', 'hi', '-', 'im_', 'ù_', 'a', '-', 'li', '-', 'li_', 'ip', '-', 'q', 'í', '-', 'du_', 'KÙ.BABBAR_', 'a', '-', 'na_', 'a', '-', 'lá', '-', 'hi', '-', 'im_', 'a', '-', 'li', '-', 'li_', 'ù_', 'hi', '-', 'na', '-', 'a_', 'b', 'a', '-', 're', '-', 'š', 'u', '-', 'nu_', 'i', '-', 'lá', '-', 'ak_', '<eos>']
['<sos>', 'a', '-', 'na_', 'É_', 'š', 'á', 'l', '-', 'ma', '-', 'a', '-', 'šùr_', 'a', '-', 'na_', 'a', '-', 'wa', '-', 'tim_', 'n', 'é', '-', 'ru', '-', 'ub', '-', 'ma_', 'um', '-', 'ma_', 'š', 'á', 'l', '-', 'ma', '-', 'a', '-', 'šù', 'r', '-', 'ma_', 'i', '-', 'a', '-', 'tí_', 'a', '-', 'na_', 'bu', '-', 'ru', '-', 'uš', '-', 'ha', '-', 'dim_', 'i', '-', 'na_', 'ma', '-', 'ak', '-', 's', 'ú', '-', 'e', '-', 'im_', 'a', '-', 'na_', 'hu', '-', 'bu', '-', 'ul_', 'ÌR_', 'a', '-', 'bu', '-', 'š', 'a', '-', 'lim_', 'š', 'a', '-', 'q', 'á', '-', 'lim_', 'i', '-', 'ra', '-', 'de', '8', '-', 'ú', '-', 'ni_', 'a', '-', 'ta_', '30_', '<textile>', 'ku', '-', 'ta', '-', 'ni_', 'ù_', 'ANŠE_', 'ṣ', 'a', '-', 'lá', '-', 'ma', '-', 'am_', 'ša_', 'ÌR_', 'ta', '-', 'lá', '-', 'q', 'é', '-', 'e_', 'um', '-', 'ma_', 'š', 'u', '-', 'be', '-', 'l', 'ú', 'm', '-', 'ma_', 'ke', '-', 'na_', 'ša_', 'Ì', 'R', '-', 'd', 'í', '-', 'a', '-', 'bu', '-', 'š', 'a', '-', 'lim_', 'al', '-', 'qé_', 'š', 'a', '-', 'li', 'm', '-', 'a', '-', 'šur_', 'ša_', 'ni', '-', 'iš_', 'a', '-', 'lim_', '<place>', 'ú', 'z', '-', 'na', '-', 't', 'í', '-', 'ni_', 'il', '5', '-', 'p', 'u', '-', 'ut_', 'um', '-', 'ma_', 'š', 'a', '-', 'li', 'm', '-', 'a', '-', 'š', 'ur', '-', 'ma_', 'a', '-', 'šar_', 'ÌR_', 'a', '-', 'na_', 'Ì', 'R', '-', 'd', 'í', '-', 'kà_', 'lá_', 'i', '-', 't', 'ù', '-', 'ru', '-', 'ú_', 'ma', '-', 'a', '-', 'na_', 'Ì', 'R', '-', 'd', 'í', '-', 'a_', 'i', '-', 't', 'ù', '-', 'wa', '-', 'ar_', 'um', '-', 'ma_', 'š', 'u', '-', 'be', '-', 'l', 'ú', 'm', '-', 'ma_', 'š', 'u', '-', 'ma_', 'a', '-', 'na_', 'ku', '-', 'a', '-', 'im_', 'i', '-', 't', 'ù', '-', 'a', '-', 'ar_', 'a', '-', 'na_', 'TÚG.HI.A_', 'ù_', 'ANŠE.HI.A_', 'a', '-', 'z', 'a', '-', 'z', 'a', '-', 'kum_', 'a', '-', 'na_', 'a', '-', 'wa', '-', 'tim_', 'a', '-', 'ni', '-', 'a', '-', 'tim_', 'k', 'à', '-', 'ru', '-', 'um_', 'k', 'à', '-', 'ni', '-', 'iš_', 'i', '-', 'd', 'í', '-', 'ni', '-', 'a', '-', 't', 'í', '-', 'ma_', 'IGI_', 'GÍR_', 'ša_', 'a', '-', 'šùr_', 'š', 'í', '-', 'bu', '-', 't', 'í', '-', 'ni', '-', 'd', 'í', '-', 'in_', 'IGI_', 'ú', '-', 'ra', '-', 'a_', 'IGI_', 'ì', '-', 'l', 'í', '-', 'dan_', 'IGI_', 'ma', '-', 'ni', '-', 'um', '-', 'b', 'a', '-', 'l', 'ú', 'm', '-', 'a', '-', 'šùr_', '<eos>']
['<sos>', 'ṭ', 'up', '-', 'p', 'u', '-', 'um_', 'ša_', '10_', 'ma', '-', 'na_', 'KÙ.BABBAR_', 'ša_', 'PÚZUR', '-', 'a', '-', 'šur_', 'ù_', 'PÚZUR', '-_', '<god>', 'IŠKUR_', 'ṭ', 'up', '-', 'p', 'u', '-', 'um_', 'ša_', '4_', 'ma', '-', 'na_', 'KÙ.BABBAR_', 'ša_', 'PÚZUR', '-', 'a', '-', 'šur_', 'ṭ', 'up', '-', 'p', 'u', '-', 'um_', 'ša_', '10_', 'ma', '-', 'na_', 'KÙ.BABBAR_', 'ša_', 'a', '-', 's', 'à', '-', 'nim_', 'ṭ', 'up', '-', 'p', 'u', '-', 'um_', 'ša_', '10_', 'ma', '-', 'na_', 'KÙ.BABBAR_', 'ša_', 'al', '-', 'p', 'ì', '-', 'lí_', 'ṭ', 'up', '-', 'p', 'u', '-', 'um_', 'ša_', '10_', 'ma', '-', 'na_', 'KÙ.BABBAR_', 'ša_', 'a', '-', 's', 'à', '-', 'nim_', 'ú_', 'PÚZUR', '-', 'a', '-', 'šur_', 'ṭ', 'up', '-', 'p', 'u', '-', 'um_', 'ša_', '5_', 'ma', '-', 'na_', 'KÙ.BABBAR_', 'ša_', 'a', '-', 'šù', 'r', '-', 'ṣ', 'ú', '-', 'lu', '-', 'li_', 'ṭ', 'up', '-', 'p', 'u', '-', 'um_', 'ša_', '17_', 'ma', '-', 'na_', '15_', 'G', 'ÌN_', 'ša_', 'e', '-', 'na', '-', 'na', '-', 'tim_', 'ṭ', 'up', '-', 'p', 'u', '-', 'um_', 'ša_', 'hu', '-', 'bu', '-', 'ul_', 'a', '-', 'bi', '-', 'ni_', 'i', '-', 'na_', 'ku', '-', 'bu', '-', 'ur', '-', 'na', '-', 'at_', 'al', '-', 'q', 'é', '-', 'šu_', '<eos>']
['<sos>', '17_', 'GÍN_', 'KÙ.BABBAR_', 'š', 'í', '-', 'im_', 'e', '-', 'ma', '-', 'ri', '-', 'im_', '30_', 'ma', '-', 'na_', 'URUDU_', 'IŠT', 'A', 'R', '-', 'p', 'í', '-', 'lá', '-', 'ah_', 'a', '-', 'na_', 'ar', '-', 'be', '-', 'e', '-', 'šu_', '<gap>', 'ù', '-', 'k', 'à', '-', 'p', 'u', '-', 'ú_', 'š', 'a', '-', 'p', 'ì', '-', 'ú', '-', 'tim_', '9_', 'ma', '-', 'na_', 'URUDU_', 'SIG5_', 'i_', 'š', 'í', '-', 'im_', 's', 'ú', '-', 'ub', '-', 'ri', '-', 'im_', '1_', 'ma', '-', 'na_', 'URUDU_', 'š', 'í', '-', 'kam_', 'iš', '-', 'tí_', 'DUMU_', 'IŠT', 'A', 'R', '-', 'b', 'a', '-', 'ni_', '2_', 'k', 'à', '-', 'ar', '-', 'pá', 't_', 'k', 'à', '-', 'mu', '-', 'nu_', 'm', 'ì', '-', 'ma_', 'a', '-', 'nim_', 'i', '-', 'na_', 'du', '-', 'ur', '-', 'hu', '-', 'm', 'ì', '-', 'it_', 'i', '-', 'b', 'a', '-', 'ší_', '10_', 'p', 'í', '-', 'ri', '-', 'k', 'à', '-', 'nu_', '1_', 'GÚ_', 'SÍG.HI.A_', '2_', 'ú', '-', 'k', 'à', '-', 'p', 'é', '-', 'e_', '80_', 'lu', '-', 'ur', '-', 'ma', '-', 'tum_', '10_', 'ma', '-', 'na_', 'Ì.GIŠ_', 's', 'à', '-', 'ar', '-', 'dam_', 's', 'à', '-', 'á', 'p', '-', 't', 'í', '-', 'nam_', 'ni', '-', 'ib', '-', 'ra', '-', 'ra', '-', 'am_', '2_', 'š', 'í', '-', 'it', '-', 're', '-', 'e_', 'ša_', 'z', 'a', '-', 'al', '-', 'pá_', '2_', 'e', '-', 'ma', '-', 're_', 'ú_', 'ù', '-', 'nu', '-', 's', 'ú', '-', 'nu_', 'm', 'ì', '-', 'ma_', 'a', '-', 'nim_', 'a', '-', 'na_', 'a', '-', 'šù', 'r', '-', 'i', '-', 'm', 'ì', '-', 'tí_', 'a', '-', 'd', 'í', '-', 'in_', '<eos>']
['<sos>', '2_', 'p', 'í', '-', 'ri', '-', 'k', 'à', '-', 'ni', '-', 'e_', 'š', 'u', '-', 'ku', '-', 'tum_', '2_', 'p', 'í', '-', 'ri', '-', 'k', 'à', '-', 'ni', '-', 'e_', 'en', '-', 'na', '-', 's', 'ú', '-', 'in_', '2_', 'p', 'í', '-', 'ri', '-', 'k', 'à', '-', 'ni_', 'ù_', 'š', 'í', '-', 'it', '-', 'ru', '-', 'um_', 'ša_', 'a', '-', 'ki', '-', 'd', 'í', '-', 'e_', '1/2_', 'GÍN_', 'KÙ.BABBAR_', 'i_', 'li', '-', 'b', 'é', '-', 'e_', 'ha', '-', 'nu', '-', 'ú_', '1_', 'p', 'í', '-', 'ri', '-', 'k', 'à', '-', 'num_', '1_', 'ša_', 'z', 'a', '-', 'al', '-', 'pá', '-', 'a_', 'ni', '-', 'ib', '-', 'ra', '-', 'ru', '-', 'um_', 'a', '-', 'zu', '-', 'ú_', 'ù_', 'DINGI', 'R', '-', 'á', 'š', '-', 'ra', '-', 'ni_', 'a', '-', 'ṣ', 'é', '-', 'er_', 'a', '-', 'm', 'ur', '-', 'IŠTAR_', 'ub', '-', 'lu', '-', 'ú_', 'm', 'ì', '-', 'ma_', 'p', 'í', '-', 'ri', '-', 'k', 'à', '-', 'ni', '-', 'e_', 'a', '-', 'ni', '-', 'ú', '-', 'tim_', 'a', '-', 'na_', 'ta', '-', 'ad', '-', 'm', 'ì', '-', 'i', 'q', '-', 'tim_', 'IŠT', 'A', 'R', '-', 'lá', '-', 'ma', '-', 'sí_', 'ta', '-', 'ta', '-', 'd', 'í', '-', 'in_', '<eos>']
['<sos>', 'i', '-', 'ku', '-', 'p', 'í', '-', 'a_', 'ù_', 'en', '-', 'um', '-', 'a', '-', 'šur_', 'i', 'ṣ', '-', 'bu', '-', 't', 'ù', '-', 'ni', '-', 'a', '-', 't', 'í', '-', 'ma_', 'um', '-', 'ma_', 'i', '-', 'ku', '-', 'p', 'ì', '-', 'a', '-', 'ma_', 'a', '-', 'na_', 'en', '-', 'um', '-', 'a', '-', 'š', 'ur', '-', 'ma_', '5_', 'GÚ_', 'URUDU_', 'ma', '-', 's', 'í', '-', 'am_', 'š', 'a', '-', 'bu', '-', 'ra', '-', 'am_', 'hu', '-', 'ub', '-', 'lam', '-', 'ma_', 'PUZUR', '4', '-_', '<god>', 'UTU_', 'li', '-', 'p', 'u', '-', 'ul', '-', 'kà_', '5_', 'GÚ_', 'URUDU_', 'ma', '-', 's', 'í', '-', 'am_', 'š', 'a', '-', 'bu', '-', 'ra', '-', 'am_', 'en', '-', 'um', '-', 'a', '-', 'šur_', 'a', '-', 'na_', 'i', '-', 'ku', '-', 'p', 'í', '-', 'a_', 'i', 'h', '-', 'bu', '-', 'ul', '-', 'ma_', 'PUZUR', '4', '-_', '<god>', 'UTU_', 'en', '-', 'um', '-', 'a', '-', 'šur_', 'e', '-', 'p', 'u', '-', 'ul_', 'um', '-', 'ma_', 'PUZUR', '4', '-_', '<god>', 'U', 'T', 'U', '-', 'ma_', 'a', '-', 'na_', '15_', 'u', '4', '-', 'me', '-', 'e_', '5_', 'GÚ_', 'UR', 'UDU', '-', 'a', '-', 'kà_', 'a', '-', 'na', '-', 'ku_', 'a', '-', 'š', 'a', '-', 'q', 'á', '-', 'lá', '-', 'ku', '-', 'um', '-', 'ma_', 'en', '-', 'um', '-', 'a', '-', 'š', 'ur', '-', 'ma_', 'š', 'u', '-', 'ma', '-', 'ba_', 'i', '-', 'na_', '15_', 'u', '4', '-', 'me', '-', 'e_', 'u', '4', '-', 'mu', '-', 'ú_', 'm', 'ì', '-', 'ma_', 'e', '-', 'ta', '-', 'at', '-', 'qú_', 'um', '-', 'ma_', 'i', '-', 'ku', '-', 'p', 'í', '-', 'a', '-', 'ma_', '5_', 'GÚ_', 'UR', 'UDU', '-', 'a', '-', 'kà_', 'ma', '-', 's', 'í', '-', 'am_', 'š', 'a', '-', 'bu', '-', 'ra', '-', 'am_', 'PUZUR', '4', '-_', '<god>', 'UTU_', 'li', '-', 'iš', '-', 'q', 'ú', '-', 'lá', '-', 'kum_', 'a', '-', 'na_', 'ṣ', 'í', '-', 'ib', '-', 'tim_', 'ma', '-', 'lá_', 'u', '4', '-', 'mu_', 'e', '-', 't', 'í', '-', 'q', 'ú', '-', 'ni', '-', 'ni_', 'i', '-', 'a', '-', 'tí_', 'URUDU_', 'a', '-', 'nim_', 'a', '-', 'na_', '4_', 'u', '4', '-', 'me_', 'DINGIR_', 'i', '-', 'š', 'a', '-', 'hi', '-', 'i', 'ṭ', '-', 'ma_', 'ha', '-', 'mu', 'š', '-', 'tum_', 'ša_', '<god>', 'IM', '-', 'ṣ', 'ú', '-', 'lu', '-', 'li_', '<big_gap>', '-_', '<gap>', 'ITU.KAM_', 'ku', '-', 'z', 'al', '-', 'li', '-', 'mu', '-', 'um_', 'ṣ', 'í', '-', 'lu', '-', 'lu_', 'um', '-', 'ma_', 'i', '-', 'ku', '-', 'p', 'í', '-', 'a', '-', 'ma_', 'a', '-', 'na_', 'en', '-', 'um', '-', 'a', '-', 'š', 'ur', '-', 'ma_', 'i', '-', 'nu', '-', 'mì_', 'a', '-', 'na_', 'p', 'u', '-', 'ru', '-', 'uš', '-', 'ha', '-', 'dim_', 't', 'é', '-', 'ra', '-', 'b', 'a', '-', 'ni_', 'ù_', 'a', '-', 'ta_', 'ša_', 'KÙ.BABBAR_', '1_', 'ma', '-', 'na_', 'ù_', '2_', 'ma', '-', 'na_', 'a', '-', 'na', '-', 'ah', '-', 'ta', '-', 'kà_', 'ta', '-', 'lá', '-', 'q', 'é', '-', 'ma_', 'ù_', 'a', '-', 'na', '-', 'ku_', 'lá', '-', 'ag', '-', 'm', 'ì', '-', 'il', '5', '-', 'kà_', 'a', '-', 'na_', 'a', '-', 'wa', '-', 'tim_', 'a', '-', 'ni', '-', 'a', '-', 'tim_', 'k', 'à', '-', 'ru', '-', 'um_', 'wa', '-', 'ah', '-', 'š', 'u', '-', 'š', 'a', '-', 'na_', 'i', '-', 'd', 'í', '-', 'ni', '-', 'a', '-', 't', 'í', '-', 'ma_', 'IGI_', 'GÍR_', 'ša_', 'a', '-', 'šu_', '<eos>']
['<sos>', 'um', '-', 'ma_', 'i', '-', 'tur', '4', '-', 'DINGI', 'R', '-', 'ma_', 'a', '-', 'na_', 'en', '-', 'um', '-', 'a', '-', 'šur_', 'ù_', 'a', '-', 'lá', '-', 'hi', '-', 'im_', 'q', 'í', '-', 'bi', '-', 'ma_', 'a', '-', 'p', 'u', '-', 'tum_', 'a', '-', 'p', 'u', '-', 'tum_', 'ra', '-', 'ma', '-', 'ku', '-', 'nu_', 'z', 'a', '-', 'ki', '-', 'a', '-', 'ma_', 'm', 'ì', '-', 'ma_', 'URUDU_', 'a', '-', 'na_', 'bu', '-', 'ru', '-', 'uš', '-', 'ha', '-', 'dim_', 'lá_', 't', 'ù', '-', 'š', 'é', '-', 'b', 'a', '-', 'lá_', 'a', '-', 'ma', '-', 't', 'um', '-', 'ma_', 'a', '-', 'b', 'a', '-', 't', 'í', '-', 'iq_', 'ú', '-', 't', 'ù', '-', 'ur_', 'd', 'í', '-', 'na', '-', 'ma_', 'KÙ.BABBAR_', 'le', '-', 'q', 'é', '-', 'a', '-', 'ma_', 't', 'í', '-', 'ib', '-', 'a', '-', 'ni', '-', 'ma_', 'a', '-', 'tal', '-', 'k', 'à', '-', 'nim_', 'a_', 'ma', '-', 'lá_', 'i_', 'pá', '-', 'ni', '-', 'tim_', 'a', '-', 'na_', 'be', '-', 'el_', 'KÙ.BABBAR_', 'ú', '-', 's', 'á', '-', 'li', '-', 'ú', '-', 'ma_', 'lá_', 'im', '-', 'gu', '5', '-', 'ru', '-', 'ni', '-', 'ni_', 'ú', '-', 'ma', '-', 'am_', 'im', '-', 'ta', '-', 'ag', '-', 'ru', '-', 'ni_', '<eos>']

In [ ]:
#Sanity Checkpoint. All rows should be an array of tokens at this point.
cleaned_complete_df.sample(5)

,oare_id,transliteration,translation
1208,c4509217-0fed-4328-8bc6-fb9fb41f229e,"[<sos>, 15_, GÍN_, KÙ.BABBAR_, i, -, na_, li, ...",15 shekels of silver is owed by Irišum son of ...
700,71112263-5009-4065-b5ff-d4ec32dd83bb,"[<sos>, a, -, na_, e, -, lá, -, ma_, q, í, -, ...","Say to Elamma, thus Aššur-rē'ī: The 2 Šulupkae..."
120,121f01b4-5a21-4703-8eee-425d568648d7,"[<sos>, um, -, ma_, ku, -, z, i, -, z, i, -, a...",From Kuziziya to Ennam-Aššur: Šu-Bēlum and Alu...
813,82b2c169-af37-4c2b-bfdd-0fa305d42fe0,"[<sos>, š, a, -, li, m, -, a, -, šùr_, ù_, š, ...",Šalim-Aššur and Šu-Bēlum son of Iddin-abum set...
353,37ea781c-687b-4e96-b8a5-c100ddc27f30,"[<sos>, um, -, ma_, a, -, šù, r, -, š, a, -, d...","Thus say Aššur-šad-ilī and Ababaya, say to Kul..."

In [ ]:
cleaned_complete_df.to_csv("processed/processed_train_complete.csv")
cleaned_incomplete_df.to_csv("processed/processed_train_incomplete.csv")

Data Preprocessing Ends Here.